### GET request to example server
GET http://localhost:8090/restapi/hello-world

###
GET http://localhost:8090/restapi/hello-world
Accept: text/html

###
GET http://localhost:8090/restapi/hello-world
Accept: application/json